// export { default as Avatar } from './avatar.component';
export { AvatarContainer as Avatar} from './avatar/avatar.container';
export { default as BottomNavigation } from './bottomNavigation.component';
// export { default as Button } from './button.component';
export { ButtonContainer as Button } from './button/button.container';
export { default as ButtonGroup } from './buttonGroup.component';
// export { default as CheckBox } from './checkbox.component';
export { CheckBoxContainer as Checkbox} from './checkbox/checkbox.container';
export { default as Dialog } from './dialog.component';
export { default as Home } from './home.component';
// export { default as Input } from './input.component';
export { InputContainer as Input } from './input/input.container';
export { default as Layout } from './layout.component';
export { default as List } from './list.component';
export { default as Popover } from './popover.component';
// export { default as Radio } from './radio.component';
export { RadioContainer as Radio } from './radio/radio.container';
export { default as RadioGroup } from './radioGroup.component';
export { default as TabBar } from './tabBar.component';
export { default as TabView } from './tabView.component';
export { default as Tooltip } from './tooltip.component';
export { default as Text } from './text.component';
// export { default as Toggle } from './toggle.component';
export { ToggleContainer as Toggle } from './toggle/toggle.container';
export { default as ViewPager } from './viewPager.component';
export { default as TopNavigation } from './topNavigation.component';
export { default as Modal } from './modal.component';
export { default as OverflowMenu } from './overflowMenu.component';
