name: CI
on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable
        env:
          COREPACK_ENABLE_DOWNLOAD_PROMPT: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - run: yarn install --immutable

      - run: yarn lint

      - run: yarn build

      - run: yarn typecheck

      - run: yarn typecheck:all

      - run: yarn test
