name: Release
on:
  push:
    branches: [master, next]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable
        env:
          COREPACK_ENABLE_DOWNLOAD_PROMPT: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          registry-url: https://registry.npmjs.org

      - run: npm install -g npm@latest

      - run: yarn install --immutable

      - run: yarn build

      - uses: changesets/action@v1
        with:
          version: yarn version-packages
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
